name: dating_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  assorted_layout_widgets: ^8.0.4
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_map: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  get_it: ^7.6.0
  google_maps_flutter: ^2.5.0
  intl: ^0.18.0
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.0.0
  #  modal_bottom_sheet: ^2.1.2
  modal_bottom_sheet: ^3.0.0-pre
  package_info_plus: ^4.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1
  timelines: ^0.1.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  workmanager: ^0.5.1
  get: ^4.6.5
  fluttertoast: ^8.2.2
  flutter_dotenv: ^5.1.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.1.0
  flutter_advanced_switch: ^3.0.1
  loading_animation_widget: ^1.2.0+4
  intl_translation: ^0.18.1
  freezed_annotation: ^2.4.1
  intl_utils: ^2.8.4
  flutter_local_notifications: ^16.1.0
  flutter_bloc: ^8.1.3

dev_dependencies:
  build_runner: ^2.4.6

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
